sudo: required
services:
    - docker

before_install:
    - docker build -t arnizzle/react-workflow -f Dockerfile.dev . 

script:
    - docker run -e CI=true arnizzle/react-workflow npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "react-workflow"
    env: "ReactWorkflow-env"
    bucket_name: "elasticbeanstalk-eu-west-2-844569641877"
    bucket_path: "react-workflow"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"

# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY


